### ISSUE TITLE
EACCES: Permission denied error

### ISSUE THREAD

**Issue by Klariff** [Kienz/homebridge-speedtest-net#2]
An error occured: Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/homebridge-speedtest-net/node_modules/speedtest-net/binaries' - Trying again in 1 min

**Comment by Kienz** [comment]
Try the following install command:
```sudo npm install -g homebridge-broadband@latest --unsafe-perm```

README is coming in the next days.

**Comment by Julien-Molina** [comment]
I have the same error on my Homebridge installed on a Raspberry Pi 3 with the last Raspbian.
I used the command you proposed to install the plugin but it didn't change anything.

I tried using Homebridge with the "Use sudo" but it didn't change anything neither I guess that is used only by the ui

I tried to help creating the folders just in case but I just go from one error to the next one  : 

- Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/homebridge-speedtest-net/node_modules/speedtest-net/binaries'
- Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/homebridge-speedtest-net/node_modules/speedtest-net/pkg'
- Error downloading speedtest CLI executable from https://bintray.com/ookla/download/download_file?file_path=ookla-speedtest-1.0.0-arm-linux.tgz: EACCES: permission denied, open '/usr/lib/node_modules/homebridge-speedtest-net/node_modules/speedtest-net/pkg/arm-linux-1.0.0.tgz'
- EACCES: permission denied, open '/usr/lib/node_modules/homebridge-speedtest-net/node_modules/speedtest-net/binaries/-1.0.0' => I stopped after this one.

Do you have any idea that I could try to help to figure out the problem ?

**Comment by Kienz** [comment]
Try the commands from https://github.com/Kienz/homebridge-speedtest-net#installation-instructions

The underlying NodeJS tool speedtest.net want to create two folders for the download fils to measure speed.

I'm looking into this problem and try to fix it.

**Comment by Julien-Molina** [comment]
It works for me, thx
